https://std-backend.onrender.com/employees/register?email=admin@gmail.com
Content-Type: application/json

[
{
"name": "sharam",
"email": "sharma@gamil.com",
"phone": "9927675982",
"password": "helo"
}
]
